### ISSUE TITLE
Device does not have front camera....

### ISSUE THREAD

**Issue by johan-schoeman** [kevalpatel2106/UserAwareVideoView#1]
I have downloaded the APK. On my Samsung S4 mini with Kitkat it displays the message "Device does not have front camera..." even though the video plays/pauses when I look at/look away from the front facing camera. Also happens on my Vodaphone with Lollipop 5.1

Other than this - a great project!

**Comment by kevalpatel2106** [comment]
Hi,
I recently fixed this bug and released the new version [1.0.1](https://github.com/kevalpatel2106/UserAwareVideoView/releases/tag/1.0.1) .

**Comment by pierrre** [comment]
Can you release a new sample apk please ?

**Comment by kevalpatel2106** [comment]
@pierrre Sure I will release it soon.

**Comment by kevalpatel2106** [comment]
@pierrre I uploaded sample apk with the latest library version 1.0.2.
