### ISSUE TITLE
Crash in sample apk

### ISSUE THREAD

**Issue by android-rk** [kevalpatel2106/UserAwareVideoView#2]
i appreciate your work buddy.
i downloaded you sample apk and install it in 3-4 phones and unfortunately app is crashing.
in one phone says front camera not deteted/found even device has front camera
in another phone it says unable to detect your eyes.

can you fix these so that i can enjoy it.

**Comment by kevalpatel2106** [comment]
Can you provide the information about the phone and android version it has? Also if possible please post the crash report here.

Thank you.

**Comment by android-rk** [comment]
yes i have gionee P4 having 4.4.2 and Le 1 having Android M
sorry i don't have crash reports.
you can check screenshot http://imgur.com/a/dCBtH

my device front camera is working proper

**Comment by kevalpatel2106** [comment]
@android-rk Were you using the latest version [1.0.1](https://github.com/kevalpatel2106/UserAwareVideoView/releases/tag/1.0.1)?

**Comment by android-rk** [comment]
i downloaded from https://github.com/kevalpatel2106/UserAwareVideoView/blob/master/apk/sample.apk
i don't know it's version weather it is 1.0.1 or something else ?

**Comment by pierrre** [comment]
The apk was released before 1.0.1

**Comment by kevalpatel2106** [comment]
@pierrre Updated the sample apk with the latest version of the library v1.0.2 .
@android-rk Can you test the latest sample apk?

You can find out more about the latest release from [here](https://github.com/kevalpatel2106/UserAwareVideoView/releases/tag/1.0.2).

**Comment by android-rk** [comment]
@kevalpatel2106  installed new apk in my 4.4.2 powered phone and app says can't play this video.
and one more issue i think you left to close camera instance in onDestroy() or onPause()  my camera app also crashing after opening you app.

**Comment by kevalpatel2106** [comment]
@android-rk 
- For the first issue, make sure you have active internet connection. Because the video is being played from the URL.
- For the second issue, I am releasing the camera. (You can see it [here](https://github.com/kevalpatel2106/UserAwareVideoView/blob/master/userawarevideoview/src/main/java/com/kevalpatel/userawarevieoview/FaceAnalyser.java#L63)) I don't see any force close while opening camera app after opening the sample app. Let me know if you have any other fix for that.

**Comment by android-rk** [comment]
great work buddy , i'm also droid dev like you,working in 5.1.1 and 6.0 but not in my 4.4.2.
all the best keep going.

**Comment by kevalpatel2106** [comment]
@android-rk Unfortunately, I don't have an android device running on 4.4.2 . Can you post the stack trace if you are getting FCs on android 4.4.2?

**Comment by pierrre** [comment]
@kevalpatel2106 it works ! Thank you !

**Comment by kevalpatel2106** [comment]
@android-rk Can you confirm if the bug still exists in lasted sample apk?
